# Generated by Django 6.0.5 on 2026-06-02 15:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название книги')),
                ('author', models.CharField(max_length=100, verbose_name='Автор')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Цена')),
                ('published_date', models.DateField(verbose_name='Дата публикации')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступна для продажи')),
                ('pages', models.PositiveIntegerField(verbose_name='Количество страниц')),
                ('cover_image', models.ImageField(blank=True, upload_to='books_covers/', verbose_name='Обложка')),
                ('book_file', models.FileField(blank=True, upload_to='books_files/', verbose_name='Электронный файл')),
                ('discount_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Промокод (не обязательно)')),
                ('reserved_count', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Количество книг для брони')),
            ],
        ),
    ]
