# Generated by Django 6.0.5 on 2026-06-16 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horse_tour', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='horsetour',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
